//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telos.Admin.Web.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Telos.Admin.Web.Models.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Alunos da Escola.
        /// </summary>
        public static string Aluno {
            get {
                return ResourceManager.GetString("Aluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alunos.
        /// </summary>
        public static string Aluno_Create_Title {
            get {
                return ResourceManager.GetString("Aluno_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string AlunoModel_Celular {
            get {
                return ResourceManager.GetString("AlunoModel_Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.E.P..
        /// </summary>
        public static string AlunoModel_Cep {
            get {
                return ResourceManager.GetString("AlunoModel_Cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string AlunoModel_CpfCode {
            get {
                return ResourceManager.GetString("AlunoModel_CpfCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF do Responsável.
        /// </summary>
        public static string AlunoModel_CpfResponsavel {
            get {
                return ResourceManager.GetString("AlunoModel_CpfResponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string AlunoModel_DataNascimento {
            get {
                return ResourceManager.GetString("AlunoModel_DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string AlunoModel_Email {
            get {
                return ResourceManager.GetString("AlunoModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string AlunoModel_Endereco {
            get {
                return ResourceManager.GetString("AlunoModel_Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Mofidicação.
        /// </summary>
        public static string AlunoModel_ModifiedDate {
            get {
                return ResourceManager.GetString("AlunoModel_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string AlunoModel_Nome {
            get {
                return ResourceManager.GetString("AlunoModel_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do Responsável.
        /// </summary>
        public static string AlunoModel_NomeReponsavel {
            get {
                return ResourceManager.GetString("AlunoModel_NomeReponsavel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.G..
        /// </summary>
        public static string AlunoModel_Rg {
            get {
                return ResourceManager.GetString("AlunoModel_Rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string AlunoModel_Telefone {
            get {
                return ResourceManager.GetString("AlunoModel_Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telos - App de Administração.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Cursos da escola.
        /// </summary>
        public static string Curso {
            get {
                return ResourceManager.GetString("Curso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curso.
        /// </summary>
        public static string Curso_Create_Title {
            get {
                return ResourceManager.GetString("Curso_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string CursoModel_CursoCode {
            get {
                return ResourceManager.GetString("CursoModel_CursoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string CursoModel_Descricao {
            get {
                return ResourceManager.GetString("CursoModel_Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duração (em meses).
        /// </summary>
        public static string CursoModel_MesesDuracao {
            get {
                return ResourceManager.GetString("CursoModel_MesesDuracao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Modificação.
        /// </summary>
        public static string CursoModel_ModifiedDate {
            get {
                return ResourceManager.GetString("CursoModel_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string CursoModel_Nome {
            get {
                return ResourceManager.GetString("CursoModel_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço Padrão (R$).
        /// </summary>
        public static string CursoModel_PrecoPadrao {
            get {
                return ResourceManager.GetString("CursoModel_PrecoPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Professores da Escola.
        /// </summary>
        public static string Professor {
            get {
                return ResourceManager.GetString("Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professor.
        /// </summary>
        public static string Professor_Create_Title {
            get {
                return ResourceManager.GetString("Professor_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celular.
        /// </summary>
        public static string ProfessorModel_Celular {
            get {
                return ResourceManager.GetString("ProfessorModel_Celular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string ProfessorModel_CpfCode {
            get {
                return ResourceManager.GetString("ProfessorModel_CpfCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Nascimento.
        /// </summary>
        public static string ProfessorModel_DataNascimento {
            get {
                return ResourceManager.GetString("ProfessorModel_DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string ProfessorModel_Email {
            get {
                return ResourceManager.GetString("ProfessorModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Modificação.
        /// </summary>
        public static string ProfessorModel_ModifiedDate {
            get {
                return ResourceManager.GetString("ProfessorModel_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string ProfessorModel_Nome {
            get {
                return ResourceManager.GetString("ProfessorModel_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string ProfessorModel_Telefone {
            get {
                return ResourceManager.GetString("ProfessorModel_Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Unidades da Escola.
        /// </summary>
        public static string Unidade {
            get {
                return ResourceManager.GetString("Unidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidade.
        /// </summary>
        public static string Unidade_Create_Title {
            get {
                return ResourceManager.GetString("Unidade_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.E.P..
        /// </summary>
        public static string UnidadeModel_Cep {
            get {
                return ResourceManager.GetString("UnidadeModel_Cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string UnidadeModel_Endereco {
            get {
                return ResourceManager.GetString("UnidadeModel_Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Modificação.
        /// </summary>
        public static string UnidadeModel_ModifiedDate {
            get {
                return ResourceManager.GetString("UnidadeModel_ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Unidade.
        /// </summary>
        public static string UnidadeModel_Nome {
            get {
                return ResourceManager.GetString("UnidadeModel_Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string UnidadeModel_UnidadeCode {
            get {
                return ResourceManager.GetString("UnidadeModel_UnidadeCode", resourceCulture);
            }
        }
    }
}
